### ISSUE TITLE
Update required but it is not possible because it breaks ffmpeg

### ISSUE THREAD

**Issue by elpideus** [distubejs/ytdl-core#152]
## Environment

- @distube/ytdl-core version:
- Node.js version:
- Operating system:

I am running ytdl-core 4.15.8 and Distube 5.0.4. This is the error that I am getting:
```
[DEMIDO] -> WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".
WARNING: Could not parse n transform function.
Please report this issue with the "1734509067132-base.js" file on https://github.com/distubejs/ytdl-core/issues.
```

If I update ytdl-core I get this error:
```
811 |       this.emit("error", err);
812 |     }).on("exit", (code, signal) => {
813 |       this.debug(`[process] exit: code=${code ?? "unknown"} signal=${signal ?? "unknown"}`);
814 |       if (!code || [0, 255].includes(code)) return;
815 |       this.debug(`[process] error: ffmpeg exited with code ${code}`);
816 |       this.emit("error", new DisTubeError("FFMPEG_EXITED", code));
                                   ^
error: ffmpeg exited with code 8
 code: "FFMPEG_EXITED"

      at S:\Development\Demido\shell\node_modules\distube\dist\index.mjs:816:30
      at emit (node:events:48:48)
      at #handleOnExit (node:child_process:449:16)
      at processTicksAndRejections (native:7:39)

Bun v1.1.33 (Windows x64)
error: script "start" exited with code 1
```

**Comment by TheBrutalSkull** [comment]
https://github.com/distubejs/ytdl-core/issues/149

**Comment by elpideus** [comment]
Okay, thank you very much!

**Comment by ab42jj** [comment]
DisTubeError [FFMPEG_EXITED]: ffmpeg exited with code 1
    at ChildProcess.<anonymous> (/home/container/node_modules/distube/src/core/DisTubeStream.ts:134:28)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:488:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  errorCode: 'FFMPEG_EXITED'
}
