### ISSUE TITLE
Error 403 using proxy agent

### ISSUE THREAD

**Issue by lltr** [distubejs/ytdl-core#157]
## Describe the bug and how to reproduce it
My usage of this library has suddenly always resulted in error 403 since 20 December, without any code changes or updates. I have narrowed it down to it using an agent, as if I stopped using the agent in `ytdl.getInfo()`, it worked. When it first stopped working, I updated node as well as the dependencies but the problem still persisted.

I have tested with other proxies and also confirmed that it is not an issue with the proxy, since the 403 message would be `Sign in to confirm if you are not a bot` and not just 403. I have tried many different proxies to confirm that, as well as buying reliable residential proxies just to confirm this.

```js
export async function takeVideoSnippet(
  videoUrl,
  timestampInSeconds,
  duration,
  outputPath,
  filename,
) {
  try {  
    let proxyConnectionString = `https://spr17axip3:XpAZafjsi0aBfl484~@isp.smartproxy.com:10001`;
    let agent = ytdl.createProxyAgent({
      uri: proxyConnectionString,
    });

    const videoInfo = await ytdl.getInfo(videoUrl, {
        agent: agent,
        playerClients: ["IOS", "WEB_CREATOR"]
      })

    const videoStreamOptions = {
      quality: "highestvideo",
      liveBuffer: 1 << 5,
    };
    const videoStream = ytdl.downloadFromInfo(videoInfo, videoStreamOptions)
    await recordVideoSegment(
      videoStream,
      0,
      duration,
      `${outputPath}/${filename}`
    );
  } catch (error) {
    throw error;
  }
}

const recordVideoSegment = promisify(
  (videoStream, startTime, duration, outputPath, callback) => {
    ffmpeg(videoStream)
      .setStartTime(startTime)
      .setDuration(duration)
      .outputOptions("-f", "mp4", "-movflags", "frag_keyframe+empty_moov")
      .outputOptions("-max_muxing_queue_size", "2048")
      .videoCodec("libx264")
      .output(outputPath)
      .on("end", () => {
        console.log(`ffmpeg-util: video saved at ${outputPath}`);
      })
      .on("error", (err) => {
        console.log("video FFmpeg Error: ");
        console.log(err);
      })
      .run();
  }
);
```

Error:
```
video FFmpeg Error:
Error: Input stream error: Status code: 403
    at PassThrough.<anonymous> (/home/lpc/playground/yt-recording-test/node_modules/.pnpm/fluent-ffmpeg@2.1.3/node_modules/fluent-ffmpeg/lib/processor.js:451:34)
    at PassThrough.emit (node:events:536:35)
    at PassThrough.emit (node:events:536:35)
    at onError (/home/lpc/playground/yt-recording-test/node_modules/.pnpm/m3u8stream@0.8.6/node_modules/m3u8stream/dist/index.js:70:16)
    at onQueuedEnd (/home/lpc/playground/yt-recording-test/node_modules/.pnpm/m3u8stream@0.8.6/node_modules/m3u8stream/dist/index.js:85:13)
    at PassThrough.<anonymous> (/home/lpc/playground/yt-recording-test/node_modules/.pnpm/m3u8stream@0.8.6/node_modules/m3u8stream/dist/queue.js:46:65)
    at PassThrough.emit (node:events:524:28)
    at ClientRequest.<anonymous> (/home/lpc/playground/yt-recording-test/node_modules/.pnpm/miniget@4.2.3/node_modules/miniget/dist/index.js:211:28)
    at Object.onceWrapper (node:events:639:26)
    at ClientRequest.emit (node:events:524:28) {
  inputStreamError: MinigetError: Status code: 403
      at ClientRequest.<anonymous> (/home/lpc/playground/yt-recording-test/node_modules/.pnpm/miniget@4.2.3/node_modules/miniget/dist/index.js:206:27)
      at Object.onceWrapper (node:events:639:26)
      at ClientRequest.emit (node:events:524:28)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:710:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
      at TLSSocket.socketOnData (node:_http_client:552:22)
      at TLSSocket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5) {
    statusCode: 403
  }
}
```

## Environment

- @distube/ytdl-core version: 4.14.4, 4.15.6, 4.15.7
- Node.js version: v22.12.0
- Operating system: Ubuntu, Alpine Docker image

**Comment by AnderRedna** [comment]
Did you solve?

**Comment by lltr** [comment]
> Did you solve?

nope

**Comment by HuakunShen** [comment]
I could use proxy agent locally and in docker container, but once I run it in github action I get the same error `Sign in to confirm if you are not a bot`, even if I run it in docker container on github action.

**Comment by TAKUANf** [comment]
Version 4.15.1 will work fine.

**Comment by lltr** [comment]
> It works fine with version 4.15.5, but higher versions seem to give 403 Error.

Just tried and it still doesn't work, I was using an even older version before this suddenly stopped working as well.
