### ISSUE TITLE
This video is unavailable

### ISSUE THREAD

**Issue by Lampropoulosss** [distubejs/ytdl-core#29]
I am simply starting node in ssh and I type these commands one by one:

1. `const ytdl = require("@distube/ytdl-core");`
2. `await ytdl.getBasicInfo("http://www.youtube.com/watch?v=aqz-KE-bpKQ")`

**Returns:** 
> Uncaught UnrecoverableError: This video is unavailable
    at exports.playError (/root/project/node_modules/@distube/ytdl-core/lib/utils.js:164:12)
    at exports.getBasicInfo (/root/project/node_modules/@distube/ytdl-core/lib/info.js:52:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Happens for every video.

## Environment

- @distube/ytdl-core version: 4.13.5
- Node.js version: v20.3.1
- Operating system: Ubuntu 24.04

**Comment by skick1234** [comment]
Provide youtube cookies (alt account) to prevent this. I don't really know why it happens but YouTube may block your ip and require sign in (like `Sign in to confirm you're not a bot` error)
