### ISSUE TITLE
AudioPlayerError: Status code: 403

### ISSUE THREAD

**Issue by babymonie** [distubejs/ytdl-core#60]
node:events:497
      throw er; // Unhandled 'error' event
      ^

AudioPlayerError: Status code: 403
    at ClientRequest.<anonymous> (C:\Users\Aloy\Downloads\yaurtrollingTm\node_modules\miniget\dist\index.js:206:27)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:519:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:698:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:540:22)
    at TLSSocket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
Emitted 'error' event on AudioPlayer instance at:
    at OggDemuxer.onStreamError (C:\Users\Aloy\Downloads\yaurtrollingTm\node_modules\@discordjs\voice\dist\index.js:1122:14)
    at Object.onceWrapper (node:events:634:26)
    at OggDemuxer.emit (node:events:531:35)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  resource: <ref *3> AudioResource {
    playStream: OggDemuxer {
      _events: {
        close: [
          [Function (anonymous)],
          [Function: onclose],
          [Function (anonymous)],
          [Function: onclose],
          [Function: bound onceWrapper] {
            listener: [Function: onFailureCallback]
          }
        ],
        error: [
          [Function: onerror],
          [Function: onError],
          [Function: onerror]
        ],
        prefinish: [Function: prefinish],
        finish: [
          [Function: onfinish],
          [Function: onfinish],
          [Function: bound onceWrapper] {
            listener: [Function: onFailureCallback]
          }
        ],
        drain: undefined,
        data: undefined,
        end: [
          [Function: onend],
          [Function: onend],
          [Function: bound onceWrapper] {
            listener: [Function: onFailureCallback]
          }
        ],
        readable: [
          [Function: bound onceWrapper] {
            listener: [Function (anonymous)]
          },
          [Function: bound onceWrapper] {
            listener: [Function: onReadableCallback]
          }
        ],
        unpipe: undefined
      },
      _readableState: ReadableState {
        highWaterMark: 16,
        buffer: [],
        bufferIndex: 0,
        length: 0,
        pipes: [],
        awaitDrainWriters: null,
        [Symbol(kState)]: 9480639,
        [Symbol(kErroredValue)]: MinigetError: Status code: 403
            at ClientRequest.<anonymous> (C:\Users\Aloy\Downloads\yaurtrollingTm\node_modules\miniget\dist\index.js:206:27)
            at Object.onceWrapper (node:events:634:26)
            at ClientRequest.emit (node:events:519:28)
            at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:698:27)
            at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
            at TLSSocket.socketOnData (node:_http_client:540:22)
            at TLSSocket.emit (node:events:519:28)
            at addChunk (node:internal/streams/readable:559:12)
            at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
            at Readable.push (node:internal/streams/readable:390:5) {
          statusCode: 403
        }
      },
      _writableState: WritableState {
        highWaterMark: 16384,
        length: 0,
        corked: 0,
        onwrite: [Function: bound onwrite],
        writelen: 0,
        bufferedIndex: 0,
        pendingcb: 0,
        [Symbol(kState)]: 17580990,
        [Symbol(kBufferedValue)]: null,
        [Symbol(kErroredValue)]: MinigetError: Status code: 403
            at ClientRequest.<anonymous> (C:\Users\Aloy\Downloads\yaurtrollingTm\node_modules\miniget\dist\index.js:206:27)
            at Object.onceWrapper (node:events:634:26)
            at ClientRequest.emit (node:events:519:28)
            at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:698:27)
            at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
            at TLSSocket.socketOnData (node:_http_client:540:22)
            at TLSSocket.emit (node:events:519:28)
            at addChunk (node:internal/streams/readable:559:12)
            at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
            at Readable.push (node:internal/streams/readable:390:5) {
          statusCode: 403
        }
      },
      allowHalfOpen: true,
      _maxListeners: undefined,
      _eventsCount: 6,
      _remainder: null,
      _head: null,
      _bitstream: null,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    edges: [
      <ref *1> {
        type: 'ffmpeg ogg',
        to: Node {
          edges: [ [Object], [Object], [Object] ],
          type: 'ogg/opus'
        },
        cost: 2,
        transformer: [Function: transformer],
        from: Node { edges: [ [Object], [Circular *1] ], type: 'arbitrary' }
      },
      <ref *2> {
        type: 'ogg/opus demuxer',
        to: Node { edges: [ [Object] ], type: 'opus' },
        cost: 1,
        transformer: [Function: transformer],
        from: Node {
          edges: [ [Circular *2], [Object], [Object] ],
          type: 'ogg/opus'
        }
      }
    ],
    metadata: null,
    volume: undefined,
    encoder: undefined,
    audioPlayer: <ref *4> AudioPlayer {
      _events: [Object: null prototype] { idle: [Function (anonymous)] },
      _eventsCount: 1,
      _maxListeners: undefined,
      _state: {
        status: 'buffering',
        resource: [Circular *3],
        onReadableCallback: [Function: onReadableCallback],
        onFailureCallback: [Function: onFailureCallback],
        onStreamError: [Function: onStreamError]
      },
      subscribers: [
        PlayerSubscription {
          connection: VoiceConnection {
            _events: [Object: null prototype],
            _eventsCount: 1,
            _maxListeners: undefined,
            rejoinAttempts: 0,
            _state: [Object],
            joinConfig: [Object],
            packets: [Object],
            receiver: [VoiceReceiver],
            debug: null,
            onNetworkingClose: [Function: bound onNetworkingClose],
            onNetworkingStateChange: [Function: bound onNetworkingStateChange],
            onNetworkingError: [Function: bound onNetworkingError],
            onNetworkingDebug: [Function: bound onNetworkingDebug],
            [Symbol(shapeMode)]: false,
            [Symbol(kCapture)]: false
          },
          player: [Circular *4]
        }
      ],
      behaviors: { noSubscriber: 'pause', maxMissedFrames: 5 },
      debug: [Function (anonymous)],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    playbackDuration: 0,
    started: false,
    silencePaddingFrames: 5,
    silenceRemaining: -1
  }
}

Node.js v20.13.1

**Comment by skick1234** [comment]
What is your ytdl-core version?

**Comment by babymonie** [comment]
> What is your ytdl-core version?
> 
> 

It's the latezg
